/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model;

import java.sql.Date;
import javafx.beans.property.IntegerProperty;
import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * This is the class for the Customers table. It is used to set and grab information from and to the table.
 * 
 * @author Francisco Trigo
 */
public class Customer {

    private int customerID; //Auto incremented in database
    private String customerName;
    private String address;
    private String postalCode;
    private String phone;
    private String country;
    private String customerArea;


    //constructor

    /**
     *
     */
    public Customer() {

    }

    /**
     *
     * @param customerID - Autogenerated in the SQL table. 
     * @param customerName -  Customer_Name field in the table
     * @param address - Address field in the table
     * @param postalCode - Postal_Code field in the table
     * @param phone - Phone field in the table
     * @param country - Country field in the table
     * @param customerArea - First_Level_Division field in the table

     */
    public Customer(int customerID, String customerName, String address, String postalCode, String phone, String country, String customerArea) {
        setCustomerID(customerID);
        setCustomerName(customerName);
        setCustomerAddress(address); 
        setCustomerPostalCode(postalCode);
        setCustomerPhone(phone);
        setCustomerArea(customerArea);


    }

    /**
     *
     * @param customerID This is customer_ID, taken from the table
     * @param customerName The customer name
     */
    public Customer(int customerID, String customerName) {
        setCustomerID(customerID); //this is Auto Incremented in the database's table
        setCustomerName(customerName);
    }

    //getters

    /**
     *
     * @return Returns the customer_ID
     */
    
    public int getCustomerID() {
        return customerID;
    }
    
    /**
     *
     * @return returns the customer's first_level_division field
     */
    public String getCustomerArea() {
        return customerArea;
    }

    /**
     *
     * @return returns the customer's name
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     *
     * @return returns the customer's address
     */
    public String getCustomerAddress() {
        return address;
    }

    /**
     *
     * @return returns the customer's postal code
     */
    public String getCustomerPostalCode() {
        return postalCode;
    }

    /**
     *
     * @return returns the customer's phone number
     */
    public String getCustomerPhone() {
        return phone;
    }

    /**
     *
     * @return returns the customer's first_level_division
     */
    public String getCustomerDivisionArea() {
        return country;
    }
    
    /**
     *
     * @return returns the customers country
     */
    public String getCustomerCountry() {
    return country;
    }



    //setters

    /**
     *
     * @param customerID Autogenerated, taken form the SQL table db
     */
    
    public void setCustomerID(int customerID) {

        this.customerID = customerID;
    }
    
    /**
     *
     * @param customerArea Sets the customer first_level_division
     */
    public void setCustomerArea(String customerArea) {
        this.customerArea = customerArea;
    }

    /**
     *
     * @param customerName sets the customer name
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    /**
     *
     * @param address sets the customer address
     */
    public void setCustomerAddress(String address) {
        this.address = address;
    }

    /**
     *
     * @param postalCode sets the customer postal code
     */
    public void setCustomerPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }

    /**
     *
     * @param phone sets the customers phone number
     */
    public void setCustomerPhone(String phone) {
        this.phone = phone;
    }

//    public void setCustomerDivisionArea(String divisionArea) {
//        this.divisionArea = divisionArea;
//    }

    /**
     *
     * @param divisionArea sets the customer first level division
     */
    
    public void setCustomerCountry(String divisionArea) {
    this.country = country;
    }

}
